004: Finalize dev script and update README
This script centralizes the multiple required scripts

diff --git a/bvz b/bvz
--- a/bvz
+++ b/bvz
@@ -8,6 +8,11 @@ LIQUIBASE_DOCKER_IMAGE=bvz/liquibase-mysql:latest
 DIST_DIR=./dist/app
 
 # =============================================================
+# Variables
+# =============================================================
+PASSWORD=""
+
+# =============================================================
 # Helpers
 # =============================================================
 
@@ -69,15 +74,18 @@ buildDist() {
 }
 
 clean() {
+    echo "Cleaning up built files"
     rm -rf $DIST_DIR/app
     rm $DIST_DIR/app.zip
 }
 
 dev() {
+    echo "Starting local dev environment"
     docker compose --profile dev up -d
 }
 
 installFrontend() {
+    echo "Setup frontend npm environment"
     docker run -v ./vue:/home/node/app -w /home/node/app -u node node:22.14.0-alpine npm install --silent
 }
 
@@ -90,8 +98,8 @@ inttest() {
 awaitDbAlive() {
     i=0
     while [[ $i -lt 10 ]]; do
-        sleep 30
         echo "------ Log check #$((i + 1))/10 ($(date)) ------"
+        sleep 30
         docker logs --tail 10 brettspielverein-db-1 2>&1 | grep "mysqld: ready for connections."
 	if [[ $? -eq 0 ]]; then
 	       return
@@ -102,7 +110,7 @@ awaitDbAlive() {
     exit 1
 }
 
-migrateDb() {
+migrateDevDb() {
     echo "Running DB Migration"
     docker compose --profile db up -d
     awaitDbAlive
@@ -111,9 +119,16 @@ migrateDb() {
         --defaults-file=/liquibase/changelog/liquibase.dev.properties update --changelogFile changelog/root.changelog.yaml
 }
 
-setup() {
+migrateProdDb() {
+    echo "Running DB PROD Migration"
+    docker run --rm -v ./db/liquibase/changelog:/liquibase/changelog $LIQUIBASE_DOCKER_IMAGE \
+        --defaults-file=/liquibase/changelog/liquibase.prod.properties update --changelogFile changelog/root.changelog.yaml
+}
+
+init() {
+    echo "Setup for development"
     buildDbDockerImage
-    migrateDb
+    migrateDevDb
 
     installFrontend
 
@@ -130,10 +145,11 @@ usage() {
 Usage: $0 [OPTION]... TARGET
 
 Options:
-  -h, --help        Show this help message and exit
+  -h, --help                Show this help message and exit
+  -p <pw>, --password <pw>  Set a password for the prod DB to <pw>
 
 Arguments:
-  TARGET            The task to execute
+  TARGET                    The task to execute
 
 Description:
   This script can be used to execute all relevant task related to building,
@@ -142,9 +158,11 @@ Description:
   TARGET is a required argument and must be one of the following values:
     - buildDist: Builds the application production ready
     - dev: Starts backend, frontend, DB and mail server in their own containers
+    - init: Prepares the project for development, by building required docker images, filling the DB and installing NPM dependencies
     - inttest: Builds the frontend and backend, and deploys them together for testing
-    - setup: Prepares the project for development, by building required docker images, filling the DB and installing NPM dependencies
     - stop: Stops any running instances.
+    - migrateDevDb: Apply the current changelog to the Dev DB.
+    - migrateProdDb: Apply the current changelog to the PROD DB, requires -p option
 
   You can combine any options in any order before specifying TARGET.
 EOF
@@ -164,6 +182,14 @@ while [[ $# -gt 0 ]]; do
     -h | --help)
         usage
         exit 0
+        ;;
+    -p | --password)
+        shift
+        if [[ $# -lt 1 ]]; then
+            echo "Error: No password to parse."
+            exit 1
+        fi
+        PASSWORD=$1
         ;;
     -*)
         echo "Unknown option: $1"
@@ -201,14 +227,24 @@ dev)
 inttest)
     inttest
     ;;
-setup)
-    setup
+init)
+    init
+    ;;
+migrateDevDb)
+    migrateDevDb
+    ;;
+migrateProdDb)
+    if [[ -z $PASSWORD ]]; then
+        echo "Password required!"
+        exit 1
+    fi
+    migrateProdDb
     ;;
 stop)
     stop
     ;;
 *)
-    echo "Error: Invalid TARGET value '$target'. Must be one of: buildDist, dev, inttest, setup, stop"
+    echo "Error: Invalid TARGET value '$target'. Must be one of: buildDist, dev, inttest, init, stop"
     usage
     exit 1
     ;;
